#+title: 电脑配置
#+author: Dylan Yang
#+date: 2025:11:21

* 工具选择

** macports

使用 macports 替代原来的 homebrew ，用编译解决自动安装的问题，还可以放弃 ruby 相关的依赖，轻松。

- emacs :: ~sudo port install emacs~
- emacs-app-devel :: ~sudo port install emacs-app-devel~
- fzf :: ~sudo port install fzf~
- fastfetch :: ~sudo port install fastfetch~
- ripgrep :: ~sudo port install ripgrep~

启动的时候，emacs 命令行版，emacs-app 客户端版。

~alias emacs-app="open -a emacs"~

** wezterm

终端模拟器，从 iTerm 和 Kitty 迁移而来。

- ~zoxide~ :: 快速跳转目录的工具，替代 ~cd~ 命令，使用 ~cargo~ 安装

** .emacs.d

Emacs 的配置文件夹做为子项目保存，配置文件更新之后需要同步更新。

- ~emacs-lsp-booster~ :: 加速工具，加速 eglot ，需要 ~cargo~ 进行安装

** python

- ~uv~ :: 使用 =uv= 工具管理 =Python= 相关的包和开发环境
- ~ty~ :: Python 类型检查器，和 =uv= 同属一家，可以 homebrew 直接安装 MacPorts 未纳入。 

  #+begin_src shell
    curl -LsSf https://astral.sh/ty/install.sh | sh
  #+end_src

  需要添加配置：

  #+begin_src shell
    echo 'eval "$(ty generate-shell-completion zsh)"' >> ~/.zshrc
  #+end_src

** flutter

安装 =fvm= 工具，用来管理 =flutter= 的包管理器

~fvm install stable~ 

** nodejs

安装 =votla= 工具，用来管理 =nodejs= 的相关工具，同时使用 =pnpm= 来替代 =npm= 。

** android

安装 android-sdk android-ndk 相关工具，使用 android-studio 最方便。


* 配置

** zsh

使用 starship 和 zsh 配置，删除 .tmux 和 ohmyzsh ，简化整体的配置。

- 新增 zoxide 命令

   #+begin_src sh
     cargo install zoxide --locked
   #+end_src

   #+begin_src shell
     # 安装 fzf 依赖
     sudo port install fzf # macos
     sudo dnf install fzf # fedora

     # 安装 zoxide 命令
     cargo install zoxide --locked
   #+end_src

   启动 zoxide ，向 =.zshrc= 中添加：

   #+begin_src shell
     # 启动 zoxide
     eval "$(zoxide init zsh)"

     # 加载 fzf 插件
     source /opt/local/share/fzf/shell/key-bindings.zsh
     source /opt/local/share/fzf/shell/completion.zsh
   #+end_src


* Mac 专用

** +mole+

不建议安装，特别是使用 MacPorts 的时候，清理给我 port 弄坏了。

Mac 清理工具，可以使用 =homebrew= 安装，但是不能使用 MacPorts 。

#+begin_src shell
  curl -fsSL https://raw.githubusercontent.com/tw93/mole/main/install.sh | bash
#+end_src

- ~jq~ :: 需要额外安全 =jq= 才能使用 ~mo optimize~ ，可以使用 ~port install jq~ 安装
